#端口号
server:
  port: 8817
  servlet:
    session:
      timeout: 30m

fileTempPath: /root/temp/

ttfPath: /root/IdeaProjects/print-service/src/main/java/com/example/printservice/service/impl/simsun.ttf

warehouse:
  one: [103,105]


logging:
  config: classpath:logging-config.xml
  level:
    root: debug
    com.hyc.printservice: debug
  file:
    path: logs
    name: log.log